<?php
/*
 *
 *
 *
 *
 *	This Codeigniter model file is automatically generated by Code Generator.
 * 	Filename 		: 	Application_form_model.php
 * 	Generated 		: 	03-14-2018|9:59:48
 **/
defined('BASEPATH') OR exit ('No direct script to access allowed');

class Application_form_model extends CI_Model 
{ 
	protected $Table = array(
		
		"this" => "tbl_application_form",
		"cycle" => "tbl_cycle",
		"status" => "tbl_status"
		);

	public $ID;
	public $Application_status_ID;
	public $Payment_mode_ID;
	public $TIN_no;
	public $DTI_SEC_CDA_registration_no;
	public $DTI_SEC_CDA_registration_date;
	public $Business_type_ID;
	public $Amendment_from_business_type_ID;
	public $Amendment_to_business_type_ID;
	public $Tax_incentive;
	public $Tax_incentive_reason;
	public $Last_name;
	public $First_name;
	public $Middle_name;
	public $Business_name;
	public $Trade_name_franchise;
	public $Business_address;
	public $Business_postal_code;
	public $Business_email_address;
	public $Business_telephone_number;
	public $Business_mobile_number;
	public $Owner_address;
	public $Owner_postal_code;
	public $Owner_email_address;
	public $Owner_telephone_number;
	public $Owner_mobile_number;
	public $Emergency_contact_person;
	public $Emergency_mobile_number;
	public $Emergency_email_address;
	public $Business_area;
	public $Total_number_employees;
	public $No_employees_within_LGU;
	public $Lessors_full_name;
	public $Lessors_full_address;
	public $Lessors_telephone_number;
	public $Lessors_mobile_number;
	public $Lessors_email_address;
	public $Lessors_monthly_rental;
	public $Application_date;

	function __construct()
    {
        parent::__construct();

        $model_list = [
          
        ];
           // load all models
		$this->load->model($model_list);
		$libray_list = [
           
        ];

        $this->load->library($libray_list);
    }




	public function getSingle_by_uid($id)
 	{
		$this->db->select('*');
		$this->db->from('tbl_application_form');
		$this->db->where('U_ID', $id);
		$query = $this->db->get()->first_row();
		// if($query !=null){
		// 	$query->Address_barangay = $this->MBarangay->Get_details($query->Barangay_ID)->Barangay;
		// 	$query->Address_purok = $this->MPurok->Get_details($query->Purok_ID)->Purok;
		// 	$this->MCycle->Application_ID = $query->ID;
		// 	$query->Cycle = $this->MCycle->getAll();
		// }
		return $query;
	}

	
}