<?php
/*
 *
 *
 *
 *
 *	This Codeigniter model file is automatically generated by Code Generator.
 * 	Filename 		: 	Payment_mode_model.php
 * 	Generated 		: 	03-14-2018|10:00:33
 **/
defined('BASEPATH') OR exit ('No direct script to access allowed');

class Payment_mode_model extends CI_Model 
{ 
	public $ID;
	public $Mode;

	function save()
 	{
		$data = array(
			'Mode'	=>	$this->Mode
		);

		try
		{
			if(empty($this->ID) || $this->ID == 0)
			{
				$this->db->insert('tbl_payment_mode', $data);
			}
			else
			{
				$this->db->where('ID', $this->ID);
				$this->db->update('tbl_payment_mode', $data);
			}
		}
		catch (Exception $ex) 
		{ 
			echo $ex->getMessage();
		}
	}

	function getAll($search = '')
 	{
		$this->db->select('*');
		$this->db->from('tbl_payment_mode');
		$query = $this->db->get();

		return $query->result();
	}

	function getSingle($id)
 	{
		$this->db->select('*');
		$this->db->from('tbl_payment_mode');
		$this->db->where('ID', $id);
		$query = $this->db->get();

		return $query->row();
	}

	function delete($id)
 	{
		try
		{
			$this->db->delete('tbl_payment_mode', array('ID' => $id));
		}		
		catch (Exception $ex) 
		{ 
			echo $ex->getMessage();
		}
	}
}